name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        type: choice
        default: warning
        options:
          - info
          - warning
          - debug
      environment:
        description: 'Environment to run against'
        type: environment
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
